apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  generateName: tfjob
  name: fashion-mnist-job-3
  namespace: kubeflow
spec:
  ttlSecondsAfterFinished: 60
  tfReplicaSpecs:
    Chief:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: tensorflow
            image: gcr.io/sqsp-gcp-sandbox-001/kubeflow-fashion-mnist-train-keras:latest
            command:
            - python
            - /opt/model.py
            - --tf-export-dir=gs://sqsp-gcp-sandbox-001-fashion-mnist-tfjob/export/001
            - --tf-mode=gcs
            - --tf-train-steps=3
            - --tf-learning-rate=0.001
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secret/gcp-credentials/user-gcp-sa.json"
            volumeMounts:
            - name: sa
              mountPath: "/secret/gcp-credentials"
              readOnly: true
          volumes:
          - name: sa
            secret:
              secretName: user-gcp-sa
    

    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: tensorflow
            image: gcr.io/sqsp-gcp-sandbox-001/kubeflow-fashion-mnist-train-keras:latest
            command:
            - python
            - /opt/model.py
            - --tf-export-dir=gs://sqsp-gcp-sandbox-001-fashion-mnist-tfjob/export/001
            - --tf-mode=gcs
            - --tf-train-steps=3
            - --tf-learning-rate=0.001
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secret/gcp-credentials/user-gcp-sa.json"
            volumeMounts:
            - name: sa
              mountPath: "/secret/gcp-credentials"
              readOnly: true
          volumes:
          - name: sa
            secret:
              secretName: user-gcp-sa