apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  generateName: tfjob
  name: fashion-mnist-job-pull-1
  namespace: kubeflow
spec:
  ttlSecondsAfterFinished: 60
  tfReplicaSpecs:
    Chief:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: tensorflow
            image: tensorflow/tensorflow:latest-py3
            command:
              - /bin/bash
              - -c
            args:  
            - >
              pip install -r /code/kubeflow-scripts/samples/train-tfjob-cpu/requirements.txt && 
              python
              /code/kubeflow-scripts/samples/train-tfjob-cpu/model.py
              --tf-export-dir=gs://sqsp-gcp-sandbox-001-fashion-mnist-tfjob/export/001
              --tf-mode=gcs
              --tf-train-steps=3
              --tf-learning-rate=0.001
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secret/gcp-credentials/user-gcp-sa.json"
            volumeMounts:
            - name: sa
              mountPath: "/secret/gcp-credentials"
              readOnly: true
            - name: code-sync
              mountPath: /code
          initContainers:
          - image: k8s.gcr.io/git-sync:v3.0.1
            name: git-data
            volumeMounts:
            - name: code-sync
              mountPath: /code
            env:
            - name: GIT_SYNC_REPO
              value: "https://github.com/melihsqsp/kubeflow-scripts.git"
            - name: GIT_SYNC_BRANCH
              value: "master"
            - name: GIT_SYNC_REV
              value: "HEAD"
            - name: GIT_SYNC_DEPTH
              value: "1"
            - name: GIT_SYNC_DEST
              value: "kubeflow-scripts"
            - name: GIT_SYNC_ONE_TIME
              value: "true"
            - name: GIT_SYNC_ROOT
              value: /code/
          volumes:
          - name: sa
            secret:
              secretName: user-gcp-sa
          - name: code-sync
            emptyDir: {}    

    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        spec:
          containers:
          - name: tensorflow
            image: tensorflow/tensorflow:latest-py3
            command:
              - /bin/bash
              - -c
            args:  
            - >
              pip install -r /code/kubeflow-scripts/samples/train-tfjob-cpu/requirements.txt && 
              python
              /code/kubeflow-scripts/samples/train-tfjob-cpu/model.py
              --tf-export-dir=gs://sqsp-gcp-sandbox-001-fashion-mnist-tfjob/export/001
              --tf-mode=gcs
              --tf-train-steps=3
              --tf-learning-rate=0.001
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/secret/gcp-credentials/user-gcp-sa.json"
            volumeMounts:
            - name: sa
              mountPath: "/secret/gcp-credentials"
              readOnly: true
            - name: code-sync
              mountPath: /code
          initContainers:
          - image: k8s.gcr.io/git-sync:v3.0.1
            name: git-data
            volumeMounts:
            - name: code-sync
              mountPath: /code
            env:
            - name: GIT_SYNC_REPO
              value: "https://github.com/melihsqsp/kubeflow-scripts.git"
            - name: GIT_SYNC_BRANCH
              value: "master"
            - name: GIT_SYNC_REV
              value: "HEAD"
            - name: GIT_SYNC_DEPTH
              value: "1"
            - name: GIT_SYNC_DEST
              value: "kubeflow-scripts"
            - name: GIT_SYNC_ONE_TIME
              value: "true"
            - name: GIT_SYNC_ROOT
              value: /code
          volumes:
          - name: sa
            secret:
              secretName: user-gcp-sa
          - name: code-sync
            emptyDir: {}